/**
 * @license MIT
 * Copyright (c) 2025-present Dispersa Contributors
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * @fileoverview Shared utilities for bundlers
 */

import type { MediaQueryFunction, SelectorFunction } from '@outputs/types'
import type { ModifierInputs, ResolverDocument } from '@resolution/types'
import { ConfigurationError } from '@shared/errors/index'
import { getSortedTokenEntries, stripInternalTokenMetadata } from '@shared/utils/token-utils'
import type { ResolvedTokens, InternalResolvedTokens, ResolvedToken } from '@shared/token-types'

function sanitizeDataAttributeName(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

function escapeCssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, ' ')
}

export type TokenGroup = {
  name: string
  tokens: ResolvedToken[]
}

export function groupTokensByType(
  tokens: ResolvedTokens,
  typeGroupMap: Record<string, string>,
): TokenGroup[] {
  const groupMap = new Map<string, ResolvedToken[]>()

  for (const [, token] of getSortedTokenEntries(tokens)) {
    const groupName = typeGroupMap[token.$type ?? ''] ?? 'Other'
    const existing = groupMap.get(groupName) ?? []
    existing.push(token)
    groupMap.set(groupName, existing)
  }

  return Array.from(groupMap.entries()).map(([name, groupTokens]) => ({
    name,
    tokens: groupTokens,
  }))
}

export function indentStr(width: number, level: number): string {
  return ' '.repeat(width * level)
}

export function buildGeneratedFileHeader(): string {
  return [
    '// Generated by Dispersa - do not edit manually',
    '// https://github.com/dispersa-core/dispersa',
  ].join('\n')
}

export function toSafeIdentifier(name: string, keywords: Set<string>, capitalize: boolean): string {
  const camel = name
    .replace(/[-._]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[-._]+$/g, '')
    .replace(/^[-._]+/g, '')

  const cased = capitalize
    ? camel.charAt(0).toUpperCase() + camel.slice(1)
    : camel.charAt(0).toLowerCase() + camel.slice(1)

  const safe = /^\d/.test(cased) ? `_${cased}` : cased

  const keyCheck = capitalize ? safe.charAt(0).toLowerCase() + safe.slice(1) : safe
  return keywords.has(keyCheck) ? `\`${safe}\`` : safe
}

export function normalizeModifierInputs(inputs: Record<string, string>): Record<string, string> {
  const normalized: Record<string, string> = {}
  for (const [key, value] of Object.entries(inputs)) {
    normalized[key.toLowerCase()] = value.toLowerCase()
  }
  return normalized
}

export function assertFileRequired(
  buildPath: string | undefined,
  outputFile: string | ((inputs: ModifierInputs) => string) | undefined,
  outputName: string,
  presetLabel: string,
): void {
  const requiresFile = buildPath !== undefined && buildPath !== ''
  if (!outputFile && requiresFile) {
    throw new ConfigurationError(
      `Output "${outputName}": file is required for ${presetLabel} output`,
    )
  }
}

export function buildStablePermutationKey(
  modifierInputs: Record<string, string>,
  dimensions: string[],
): string {
  return dimensions.map((dimension) => `${dimension}=${modifierInputs[dimension] ?? ''}`).join('|')
}

export function resolveSelector(
  selector: string | SelectorFunction | undefined,
  modifierName: string,
  context: string,
  isBase: boolean,
  allModifierInputs: Record<string, string>,
): string {
  if (typeof selector === 'function') {
    return selector(modifierName, context, isBase, allModifierInputs)
  }
  if (typeof selector === 'string') {
    return selector
  }
  if (isBase) {
    return ':root'
  }

  const attrName = sanitizeDataAttributeName(modifierName)
  const attrValue = escapeCssString(context)
  return `[data-${attrName}="${attrValue}"]`
}

export function resolveMediaQuery(
  mediaQuery: string | MediaQueryFunction | undefined,
  modifierName: string,
  context: string,
  isBase: boolean,
  allModifierInputs: Record<string, string>,
): string {
  if (typeof mediaQuery === 'function') {
    return mediaQuery(modifierName, context, isBase, allModifierInputs)
  }
  if (typeof mediaQuery === 'string') {
    return mediaQuery
  }
  return ''
}

export function stripInternalMetadata(tokens: InternalResolvedTokens): ResolvedTokens {
  return stripInternalTokenMetadata(tokens)
}

export function generatePermutationKey(
  modifierInputs: Record<string, string>,
  resolver: ResolverDocument,
  isBase: boolean,
): string {
  if (isBase) {
    return 'base'
  }

  const metadata = buildMetadata(resolver)
  const normalizedInputs = normalizeModifierInputs(modifierInputs)
  const defaults = metadata.defaults

  const differences: Array<{ name: string; value: string }> = []
  for (const dimension of metadata.dimensions) {
    const value = normalizedInputs[dimension]
    if (value !== undefined && value !== defaults[dimension]) {
      differences.push({ name: dimension, value })
    }
  }

  if (differences.length === 1 && differences[0]) {
    const diff = differences[0]
    return `${diff.name}-${diff.value}`
  }

  return buildStablePermutationKey(normalizedInputs, metadata.dimensions)
}

export function isBasePermutation(
  modifierInputs: Record<string, string>,
  defaults: Record<string, string>,
): boolean {
  const normalizedInputs = normalizeModifierInputs(modifierInputs)
  const normalizedDefaults = normalizeModifierInputs(defaults)
  return Object.entries(normalizedDefaults).every(([key, value]) => normalizedInputs[key] === value)
}

export function buildInMemoryOutputKey(params: {
  outputName: string
  extension: string
  modifierInputs: Record<string, string>
  resolver: ResolverDocument
  defaults: Record<string, string>
}): string {
  const { outputName, extension, modifierInputs, resolver, defaults } = params
  const permutationKey = generatePermutationKey(
    modifierInputs,
    resolver,
    isBasePermutation(modifierInputs, defaults),
  )
  return `${outputName}-${permutationKey}.${extension}`
}

export type BundleMetadata = {
  dimensions: string[]
  defaults: Record<string, string>
}

export function buildMetadata(resolver: ResolverDocument): BundleMetadata {
  const metadata: BundleMetadata = {
    dimensions: [],
    defaults: {},
  }

  if (resolver.modifiers) {
    for (const [name, modifier] of Object.entries(resolver.modifiers)) {
      const normalizedName = name.toLowerCase()
      const defaultContext = modifier.default ?? Object.keys(modifier.contexts)[0] ?? ''
      metadata.dimensions.push(normalizedName)
      metadata.defaults[normalizedName] = defaultContext.toLowerCase()
    }
  }

  return metadata
}

export async function resolveResolverDocument(
  input: string | ResolverDocument,
): Promise<ResolverDocument> {
  if (typeof input === 'string') {
    const { ResolverLoader } = await import('@adapters/filesystem/resolver-loader')
    const loader = new ResolverLoader({})
    return await loader.loadDocument(input)
  }
  return input
}

export function countModifierDifferences(
  currentInputs: Record<string, string>,
  baseInputs: Record<string, string>,
): number {
  const normalizedCurrent = normalizeModifierInputs(currentInputs)
  const normalizedBase = normalizeModifierInputs(baseInputs)
  let count = 0
  for (const [key, value] of Object.entries(normalizedCurrent)) {
    if (value !== normalizedBase[key]) {
      count++
    }
  }
  return count
}

export function getExpectedSource(
  currentInputs: Record<string, string>,
  baseInputs: Record<string, string>,
): string {
  const normalizedCurrent = normalizeModifierInputs(currentInputs)
  const normalizedBase = normalizeModifierInputs(baseInputs)
  for (const [key, value] of Object.entries(normalizedCurrent)) {
    if (value !== normalizedBase[key]) {
      return `${key}-${value}`
    }
  }
  return 'base'
}

export function parseModifierSource(source: string): [modifierName: string, context: string] {
  const dashIndex = source.indexOf('-')
  if (dashIndex === -1) {
    return [source, '']
  }
  return [source.slice(0, dashIndex), source.slice(dashIndex + 1)]
}

export function filterTokensBySource(
  tokens: InternalResolvedTokens,
  expectedSource: string,
): InternalResolvedTokens {
  const filtered: InternalResolvedTokens = {}
  const expected = expectedSource.toLowerCase()

  for (const [name, token] of Object.entries(tokens)) {
    const source =
      typeof token._sourceModifier === 'string' ? token._sourceModifier.toLowerCase() : ''

    if (source !== '' && source === expected) {
      filtered[name] = token
    }
  }

  return filtered
}

export function filterTokensFromSets(tokens: InternalResolvedTokens): InternalResolvedTokens {
  const filtered: InternalResolvedTokens = {}

  for (const [name, token] of Object.entries(tokens)) {
    const hasModifierSource =
      typeof token._sourceModifier === 'string' && token._sourceModifier !== ''
    if (!hasModifierSource) {
      filtered[name] = token
    }
  }

  return filtered
}

export function resolveBaseFileName(
  fileName: string | ((modifierInputs: ModifierInputs) => string),
  defaults: ModifierInputs,
): string {
  if (typeof fileName === 'function') {
    return fileName({ ...defaults, _base: 'true' })
  }

  if (/\{.+?\}/.test(fileName)) {
    const baseInputs = Object.fromEntries(Object.keys(defaults).map((k) => [k, 'base']))
    return collapseBaseSegments(interpolatePattern(fileName, baseInputs))
  }

  const extMatch = fileName.match(/(\.[^.]+)$/)
  const extension = extMatch ? extMatch[1] : ''
  const baseName = extension ? fileName.slice(0, -extension.length) : fileName
  return `${baseName}-base${extension}`
}

function collapseBaseSegments(value: string): string {
  let result = value
  let previous = ''
  while (result !== previous) {
    previous = result
    result = result.replace(/\bbase([/-])base\b/, 'base')
  }
  return result
}

export function interpolatePattern(pattern: string, modifierInputs: ModifierInputs): string {
  let result = pattern

  for (const [key, value] of Object.entries(modifierInputs)) {
    result = result.replaceAll(`{${key}}`, value)
  }
  return result
}

export function resolveFileName(
  fileName: string | ((modifierInputs: ModifierInputs) => string),
  modifierInputs: ModifierInputs,
): string {
  if (typeof fileName === 'function') {
    return fileName(modifierInputs)
  }

  if (/\{.+?\}/.test(fileName)) {
    return interpolatePattern(fileName, modifierInputs)
  }

  const extMatch = fileName.match(/(\.[^.]+)$/)
  const extension = extMatch ? extMatch[1] : ''
  const baseName = extension ? fileName.slice(0, -extension.length) : fileName

  const modifierSuffix = Object.entries(modifierInputs)
    .sort(([keyA], [keyB]) => keyA.localeCompare(keyB))
    .map(([key, value]) => `${key}-${value}`)
    .join('-')

  if (modifierSuffix) {
    return `${baseName}-${modifierSuffix}${extension}`
  }

  return fileName
}
