name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe the problem you're trying to solve and what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? Is it related to a frustration with the current behavior?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like. Include API examples or pseudocode if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, or references that help explain the feature.
