// Design Tokens Preview — SwiftUI App
// Showcases Adobe Spectrum tokens generated by Dispersa

import SwiftUI

@main
struct DesignTokensPreviewApp: App {
    var body: some Scene {
        WindowGroup {
            TokenShowcase()
        }
    }
}
