// Generated by Dispersa - do not edit manually
// https://github.com/timges/dispersa

import Foundation
import SwiftUI

public struct ShadowStyle {
    public let color: Color
    public let radius: CGFloat
    public let x: CGFloat
    public let y: CGFloat
}

public enum SpectrumTokens {
    public enum Colors {
        /// Accent background (Spectrum: accent-background-color-default → accent-color-900)
        public nonisolated(unsafe) static let aliasAccentBackgroundDefault = Color(red: 0.231, green: 0.388, blue: 0.984)
        /// Accent background hover (Spectrum: accent-background-color-hover → accent-color-1000)
        public nonisolated(unsafe) static let aliasAccentBackgroundHover = Color(red: 0.153, green: 0.302, blue: 0.918)
        /// Page background (Spectrum: background-base-color → gray-25)
        public nonisolated(unsafe) static let aliasBackgroundBase = Color(red: 1, green: 1, blue: 1)
        /// First layer surface (Spectrum: background-layer-1-color → gray-50)
        public nonisolated(unsafe) static let aliasBackgroundLayer1 = Color(red: 0.973, green: 0.973, blue: 0.973)
        /// Second layer surface (Spectrum: background-layer-2-color)
        public nonisolated(unsafe) static let aliasBackgroundLayer2 = Color(red: 0.953, green: 0.953, blue: 0.953)
        /// Default border color
        public nonisolated(unsafe) static let aliasBorderDefault = Color(red: 0.855, green: 0.855, blue: 0.855)
        /// Hover border color
        public nonisolated(unsafe) static let aliasBorderHover = Color(red: 0.776, green: 0.776, blue: 0.776)
        /// Disabled background (Spectrum: disabled-background-color → gray-100)
        public nonisolated(unsafe) static let aliasDisabledBackground = Color(red: 0.914, green: 0.914, blue: 0.914)
        /// Focus ring color (Spectrum: focus-indicator-color → blue-800)
        public nonisolated(unsafe) static let aliasFocusIndicator = Color(red: 0.294, green: 0.459, blue: 1)
        /// Negative background (Spectrum: negative-background-color-default → negative-color-900)
        public nonisolated(unsafe) static let aliasNegativeBackgroundDefault = Color(red: 0.745, green: 0.122, blue: 0.063)
        /// Neutral background (Spectrum: neutral-background-color-default → gray-800)
        public nonisolated(unsafe) static let aliasNeutralBackgroundDefault = Color(red: 0.161, green: 0.161, blue: 0.161)
        /// Neutral background hover (Spectrum: neutral-background-color-hover → gray-900)
        public nonisolated(unsafe) static let aliasNeutralBackgroundHover = Color(red: 0.075, green: 0.075, blue: 0.075)
        /// Notice background (Spectrum: notice-background-color-default → notice-color-600)
        public nonisolated(unsafe) static let aliasNoticeBackgroundDefault = Color(red: 0.878, green: 0.467, blue: 0)
        /// Positive background (Spectrum: positive-background-color-default → positive-color-900)
        public nonisolated(unsafe) static let aliasPositiveBackgroundDefault = Color(red: 0, green: 0.408, blue: 0.133)
        /// Disabled text
        public nonisolated(unsafe) static let aliasTextDisabled = Color(red: 0.776, green: 0.776, blue: 0.776)
        /// Text on accent backgrounds
        public nonisolated(unsafe) static let aliasTextOnAccent = Color(red: 1, green: 1, blue: 1)
        /// Primary text
        public nonisolated(unsafe) static let aliasTextPrimary = Color(red: 0.075, green: 0.075, blue: 0.075)
        /// Secondary text
        public nonisolated(unsafe) static let aliasTextSecondary = Color(red: 0.314, green: 0.314, blue: 0.314)
        /// Spectrum blue-1000
        public nonisolated(unsafe) static let blue1000 = Color(red: 0.153, green: 0.302, blue: 0.918)
        /// Spectrum blue-1100
        public nonisolated(unsafe) static let blue1100 = Color(red: 0.114, green: 0.243, blue: 0.812)
        /// Spectrum blue-400
        public nonisolated(unsafe) static let blue400 = Color(red: 0.675, green: 0.812, blue: 0.992)
        /// Spectrum blue-600
        public nonisolated(unsafe) static let blue600 = Color(red: 0.447, green: 0.62, blue: 0.992)
        /// Spectrum blue-800
        public nonisolated(unsafe) static let blue800 = Color(red: 0.294, green: 0.459, blue: 1)
        /// Spectrum blue-900
        public nonisolated(unsafe) static let blue900 = Color(red: 0.231, green: 0.388, blue: 0.984)
        /// Spectrum gray-100
        public nonisolated(unsafe) static let gray100 = Color(red: 0.914, green: 0.914, blue: 0.914)
        /// Spectrum gray-200
        public nonisolated(unsafe) static let gray200 = Color(red: 0.882, green: 0.882, blue: 0.882)
        /// Spectrum gray-25 (lightest)
        public nonisolated(unsafe) static let gray25 = Color(red: 1, green: 1, blue: 1)
        /// Spectrum gray-300
        public nonisolated(unsafe) static let gray300 = Color(red: 0.855, green: 0.855, blue: 0.855)
        /// Spectrum gray-400
        public nonisolated(unsafe) static let gray400 = Color(red: 0.776, green: 0.776, blue: 0.776)
        /// Spectrum gray-50
        public nonisolated(unsafe) static let gray50 = Color(red: 0.973, green: 0.973, blue: 0.973)
        /// Spectrum gray-500
        public nonisolated(unsafe) static let gray500 = Color(red: 0.561, green: 0.561, blue: 0.561)
        /// Spectrum gray-600
        public nonisolated(unsafe) static let gray600 = Color(red: 0.443, green: 0.443, blue: 0.443)
        /// Spectrum gray-700
        public nonisolated(unsafe) static let gray700 = Color(red: 0.314, green: 0.314, blue: 0.314)
        /// Spectrum gray-75
        public nonisolated(unsafe) static let gray75 = Color(red: 0.953, green: 0.953, blue: 0.953)
        /// Spectrum gray-800
        public nonisolated(unsafe) static let gray800 = Color(red: 0.161, green: 0.161, blue: 0.161)
        /// Spectrum gray-900 (darkest)
        public nonisolated(unsafe) static let gray900 = Color(red: 0.075, green: 0.075, blue: 0.075)
        /// Spectrum green-1000
        public nonisolated(unsafe) static let green1000 = Color(red: 0, green: 0.349, blue: 0.106)
        /// Spectrum green-600
        public nonisolated(unsafe) static let green600 = Color(red: 0.063, green: 0.588, blue: 0.235)
        /// Spectrum green-800
        public nonisolated(unsafe) static let green800 = Color(red: 0.012, green: 0.467, blue: 0.165)
        /// Spectrum green-900
        public nonisolated(unsafe) static let green900 = Color(red: 0, green: 0.408, blue: 0.133)
        /// Spectrum orange-600
        public nonisolated(unsafe) static let orange600 = Color(red: 0.878, green: 0.467, blue: 0)
        /// Spectrum orange-800
        public nonisolated(unsafe) static let orange800 = Color(red: 0.741, green: 0.337, blue: 0)
        /// Spectrum orange-900
        public nonisolated(unsafe) static let orange900 = Color(red: 0.667, green: 0.282, blue: 0)
        /// Spectrum red-1000
        public nonisolated(unsafe) static let red1000 = Color(red: 0.667, green: 0.082, blue: 0.035)
        /// Spectrum red-600
        public nonisolated(unsafe) static let red600 = Color(red: 0.918, green: 0.282, blue: 0.227)
        /// Spectrum red-800
        public nonisolated(unsafe) static let red800 = Color(red: 0.816, green: 0.161, blue: 0.094)
        /// Spectrum red-900
        public nonisolated(unsafe) static let red900 = Color(red: 0.745, green: 0.122, blue: 0.063)
        /// Static black
        public nonisolated(unsafe) static let staticBlack = Color(red: 0, green: 0, blue: 0)
        /// Static white
        public nonisolated(unsafe) static let staticWhite = Color(red: 1, green: 1, blue: 1)
    }

    public enum Spacing {
        public nonisolated(unsafe) static let borderWidth100: CGFloat = 1
        public nonisolated(unsafe) static let borderWidth200: CGFloat = 2
        public nonisolated(unsafe) static let cornerRadius100: CGFloat = 4
        public nonisolated(unsafe) static let cornerRadius200: CGFloat = 5
        public nonisolated(unsafe) static let cornerRadius500: CGFloat = 8
        public nonisolated(unsafe) static let cornerRadius75: CGFloat = 3
        public nonisolated(unsafe) static let cornerRadius800: CGFloat = 16
        public nonisolated(unsafe) static let _100: CGFloat = 8
        public nonisolated(unsafe) static let _200: CGFloat = 12
        public nonisolated(unsafe) static let _300: CGFloat = 16
        public nonisolated(unsafe) static let _400: CGFloat = 24
        public nonisolated(unsafe) static let _50: CGFloat = 2
        public nonisolated(unsafe) static let _500: CGFloat = 32
        public nonisolated(unsafe) static let _600: CGFloat = 40
        public nonisolated(unsafe) static let _75: CGFloat = 4
        public nonisolated(unsafe) static let fontSize100: CGFloat = 14
        public nonisolated(unsafe) static let fontSize200: CGFloat = 16
        public nonisolated(unsafe) static let fontSize300: CGFloat = 18
        public nonisolated(unsafe) static let fontSize400: CGFloat = 20
        public nonisolated(unsafe) static let fontSize500: CGFloat = 22
        public nonisolated(unsafe) static let fontSize75: CGFloat = 12
    }

    public enum Durations {
        public nonisolated(unsafe) static let duration100: TimeInterval = 0.13
        public nonisolated(unsafe) static let duration200: TimeInterval = 0.25
        public nonisolated(unsafe) static let duration300: TimeInterval = 0.4
    }

    public enum Shadows {
        /// Subtle card shadow
        public nonisolated(unsafe) static let _100 = ShadowStyle(color: Color(red: 0, green: 0, blue: 0, opacity: 0.12), radius: 4.0, x: 0.0, y: 1.0)
        /// Popover / dropdown shadow
        public nonisolated(unsafe) static let _200 = ShadowStyle(color: Color(red: 0, green: 0, blue: 0, opacity: 0.16), radius: 16.0, x: 0.0, y: 4.0)
        /// Modal shadow
        public nonisolated(unsafe) static let _300 = ShadowStyle(color: Color(red: 0, green: 0, blue: 0, opacity: 0.24), radius: 28.0, x: 0.0, y: 8.0)
    }

    public enum Fonts {
        /// Spectrum sans-serif font stack
        public nonisolated(unsafe) static let fontFamilySans: String = "Adobe Clean"
        /// Spectrum serif font stack
        public nonisolated(unsafe) static let fontFamilySerif: String = "Adobe Clean Serif"
    }

    public enum FontWeights {
        public nonisolated(unsafe) static let fontWeightBlack: Font.Weight = Font.Weight.black
        public nonisolated(unsafe) static let fontWeightBold: Font.Weight = Font.Weight.bold
        public nonisolated(unsafe) static let fontWeightExtraBold: Font.Weight = Font.Weight.heavy
        public nonisolated(unsafe) static let fontWeightLight: Font.Weight = Font.Weight.light
        public nonisolated(unsafe) static let fontWeightMedium: Font.Weight = Font.Weight.medium
        public nonisolated(unsafe) static let fontWeightRegular: Font.Weight = Font.Weight.regular
    }

}
